name: newman staging test
on:
  workflow_call:
    secrets:
      POSTMAN_API_KEY:
        description: "Your Postman API Key"
        required: true

jobs:
  newman-staging-test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: setup
        run: |
          echo POSTMAN_STAGING_ENVIRONMENT_UID=8335769-71b897a7-0821-48d8-8f65-a5fa7a721ee1 >> $GITHUB_ENV
          echo EVENTS=8335769-57d4b952-2d41-406f-8deb-9d8ed1815a08 >> $GITHUB_ENV
          echo SPL=8335769-d628ae78-fc24-4f02-a4af-c1d7e6da2cdd >> $GITHUB_ENV
          echo ORDERS=8335769-eefa09ad-877c-42fe-988d-c66e776901e2 >> $GITHUB_ENV
          echo PRODUCTS=8335769-b4b1e974-546c-4bac-b97b-90cb5a548bed >> $GITHUB_ENV
          echo VOUCHERS=8335769-336d3998-7e80-40ab-b24f-fe09cb0a9905 >> $GITHUB_ENV
          echo PUBLIC_REST=8335769-670c4fd5-d443-45ad-ba9f-d04c85839ca6 >> $GITHUB_ENV
          echo AUTHENTICATION=8335769-200f3c23-6d6c-4857-9f28-65c3a69a8859 >> $GITHUB_ENV

      - name: execute Events Tests
        uses: matt-ball/newman-action@master
        if: always()
        with:
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
          collection: ${{ env.EVENTS }}
          environment: ${{ env.POSTMAN_STAGING_ENVIRONMENT_UID }}

      - name: execute SeatingPlan Tests
        uses: matt-ball/newman-action@master
        if: always()
        with:
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
          collection: ${{ env.SPL }}
          environment: ${{ env.POSTMAN_STAGING_ENVIRONMENT_UID }}

      - name: execute Orders Tests
        uses: matt-ball/newman-action@master
        if: always()
        with:
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
          collection: ${{ env.ORDERS }}
          environment: ${{ env.POSTMAN_STAGING_ENVIRONMENT_UID }}

      - name: execute Products Tests
        uses: matt-ball/newman-action@master
        if: always()
        with:
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
          collection: ${{ env.PRODUCTS }}
          environment: ${{ env.POSTMAN_STAGING_ENVIRONMENT_UID }}

      - name: execute Vouchers Tests
        uses: matt-ball/newman-action@master
        if: always()
        with:
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
          collection: ${{ env.VOUCHERS }}
          environment: ${{ env.POSTMAN_STAGING_ENVIRONMENT_UID }}

      - name: execute Public REST Tests
        uses: matt-ball/newman-action@master
        if: always()
        with:
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
          collection: ${{ env.PUBLIC_REST }}
          environment: ${{ env.POSTMAN_STAGING_ENVIRONMENT_UID }}

      - name: execute Authentication Tests
        uses: matt-ball/newman-action@master
        if: always()
        with:
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
          collection: ${{ env.AUTHENTICATION }}
          environment: ${{ env.POSTMAN_STAGING_ENVIRONMENT_UID }}
